packages:
  - './standard/scripts'
  - './standard/tests'
  - './standard/bundle'
  - './standard/packages/*'
  - './premium/tests'
  - './premium/bundle'
  - './premium/packages/*'
  - './theming/*'
  - './scripts'
  - './contrib/*'
  - './examples/*'
