packages:
  - './standard/scripts'
  - './standard/packages/*'
  - './premium/packages/*'
  - './theming/*'
  - './scripts'
  - './examples/*'

  # trouble building. think about removing support
  - '!./examples/next12'
  - '!./examples/next12-scheduler'
