packages:
  - './standard/scripts'
  - './standard/packages/*'
  - './standard/theming/*'
  - './premium/packages/*'
  - './theming/*'
  - './scripts'
  - './contrib/*'
  - './examples/*'
  - './examples-v7/*'

  # temporarily disable react
  - '!./contrib/react'
  - '!./examples/react*'
  - '!./examples/next*'
  - '!./examples/t3-app'
  - '!./examples/remix'
  - '!./theming/ui-shadcn'
  - '!./theming/ui-mui'
  - '!./theming/ui-mui-tailwind'
  - '!./theming/ui-default-react-tailwind'
  - '!./theming/demo-react'
