
#
# NOTE: keep this synced with workspace repo's config!!!!!!!!!!!
#

name: CI
on:
  push:
    branches:
      - newrepo
  # pull_request:
  #   branches:
  #     - main

env:
  TZ: "America/New_York"

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup PNPM
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 8.6.3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.13.0
          cache: 'pnpm'

      - name: Setup Turbo cache
        uses: actions/cache@v3
        with:
          path: node_modules/.cache/turbo
          key: turbo-${{ github.job }}-${{ github.ref_name }}-${{ github.sha }}
          restore-keys: turbo-${{ github.job }}-${{ github.ref_name }}-

      - name: Install Dependencies
        run: pnpm install

      - name: Install Git-Subrepo
        # https://github.com/ingydotnet/git-subrepo?tab=readme-ov-file#installation
        shell: bash
        run: |
          source ./scripts/git-subrepo/.rc
          echo "PATH:$PATH"
          git-subrepo version

      - name: Lint
        run: pnpm run lint

      - name: Build
        run: pnpm run build

      # TODO: solve flaky tests
      # - name: Test
      #   run: pnpm run test
