name: Stage Release
on:
  push:
    branches:
      - newrepo

env:
  TZ: "America/New_York"

jobs:
  stage-release:
    name: Stage Release
    if: >
      github.repository == 'fullcalendar/fullcalendar-workspace' &&
      !contains(github.event.head_commit.message, 'staged-release') &&
      !contains(github.event.head_commit.message, 'no-stage')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup PNPM
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 8.6.3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.13.0
          cache: 'pnpm'

      # - name: Setup Turbo Cache
      #   uses: actions/cache@v3
      #   with:
      #     path: node_modules/.cache/turbo
      #     key: turbo-${{ github.job }}-${{ github.ref_name }}-${{ github.sha }}
      #     restore-keys: turbo-${{ github.job }}-${{ github.ref_name }}-

      - name: Install Dependencies
        run: |
          pnpm install \
          --filter '@fullcalendar/*...' \
          --filter '@fullcalendar-scripts/*...' \
          --filter '@fullcalendar-tests/*...' \
          --filter '!./contrib/**' \

      - name: Bump Versions
        run: |
          pnpm run version

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          branch: staged-release
          commit-message: Staged Release Bump
          delete-branch: true # delete old branch (if no open PRs) before creating new
          title: Staged Release
          body: Staged release baby!!!
