name: Test GH
on:
  push:
    branches:
      - newrepo

env:
  TZ: "America/New_York"
  GH_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }}

jobs:
  test-gh:
    name: Test GH
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup PNPM
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 8.6.3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.13.0
          cache: 'pnpm'

      - name: Install Dependencies
        run: |
          pnpm \
          --filter 'fullcalendar...' \
          --filter 'fullcalendar-scheduler...' \
          --filter '@fullcalendar/*...' \
          --filter '@fullcalendar-scripts/*...' \
          --filter '@fullcalendar-tests/*...' \
          --filter '!./contrib/**' \
          install

      - name: Debug Token
        run: |
          echo "This is the token!!!: $GH_TOKEN"

      - name: Sync Repos
        run: pnpm run sync-repos
