name: Test GH
on:
  push:
    branches:
      - newrepo

env:
  TZ: "America/New_York"

jobs:
  test-gh:
    name: Test GH
    runs-on: ubuntu-latest
    environment: Production
    env:
      GH_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }} # for GitHub CLI

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.RELEASE_GITHUB_TOKEN }} # for git-subrepo pull/push later on
          fetch-depth: 0 # fetches ALL history. needed for git-subrepo operations

      # for git-subrepo pull/push later on
      - name: Setup Git User
        run: |
          git config --global user.name "${{ github.triggering_actor }}" && \
          git config --global user.email "${{ github.triggering_actor }}@users.noreply.github.com" && \
          git config -l

      - name: Setup PNPM
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 8.6.3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.13.0
          cache: 'pnpm'

      - name: Install Dependencies
        run: |
          pnpm \
          --filter 'fullcalendar...' \
          --filter 'fullcalendar-scheduler...' \
          --filter '@fullcalendar/*...' \
          --filter '@fullcalendar-scripts/*...' \
          --filter '@fullcalendar-tests/*...' \
          --filter '!./contrib/**' \
          install

      - name: Sync Repos
        run: |
          git config -l && \
          pnpm run sync-repos
